apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: slashflea/udagram-api-feed:v2
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_PROFILE
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: JWT_SECRET
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: URL
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    run: backend-feed