script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed slashflea/udagram-api-feed:v1
  - docker tag udagram-api-user slashflea/udagram-api-user:v1
  - docker tag udagram-frontend slashflea/udagram-frontend:v1
  - docker tag udagram-reverseproxy slashflea/udagram-reverseproxy:v1

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push slashflea/udagram-api-feed:v1
  - docker push slashflea/udagram-api-user:v1
  - docker push slashflea/udagram-frontend:v1
  - docker push slashflea/udagram-reverseproxy:v1
